const colours = {
    PRIMARY_COLOUR_DARK: "#303F9F",
    PRIMARY_COLOUR: "#3F51B5",
    PRIMARY_COLOUR_LIGHT: "#C5CAE9",
    PRIMARY_COLOUR_ICON: "#FFFFFF",
    ACCENT_COLOUR: "#FF5722",
    PRIMARY_COLOUR_TEXT: "#212121",
    SECONDARY_COLOUR_TEXT: "#757575",
    DIVIDER_COLOUR: "#BDBDBD"
};

export default colours;